name: weldblog
favicon: null
layout_spectrum: 0.30823514168150723
typography_spectrum: 0.5700821671634912
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.41732477280311286
  lightness: 0.30341050028800964
  saturation: 0.5206917820032686
  rhythmicContrast: 0.14072507247328758
purpose: []
