name: weldblog
favicon: null
layout_spectrum: 0.2486
typography_spectrum: 0.63776
title: "Robert's weld experience"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffdff'
    - '#090513'
    - '#dcbb92'
    - '#4675a3'
    - '#b43c2b'
  brandStrength: 0.1875
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
