name: weldblog
favicon: null
layout_spectrum: 0.16582
typography_spectrum: 0.63776
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#212121'
    - '#eada01'
    - '#5a5a5a'
    - '#a6ade3'
  brandStrength: 0.1875
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
